server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql-server:3306/pratico?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: default
    database-change-log-lock-table: PRATICO_DATABASECHANGELOGLOCK
    database-change-log-table: PRATICO_DATABASECHANGELOG
    url: jdbc:mysql://mysql-server:3306/pratico?createDatabaseIfNotExist=true
    default-schema: pratico
    user: root
    password: root
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 dia
      refresh-token:
        expiration: 604800000 # 7 dias
